# Generated by Django 5.0.2 on 2024-02-19 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "tag", "verbose_name_plural": "tags"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ("-is_done", "created_at"),
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
            },
        ),
    ]
